import 'dotenv/config'
import cron from 'node-cron'
import { createApp } from './app'
import { generateUpcomingTrips } from './jobs/generateTrips'
import { purgeExpiredHolds } from './jobs/purgeExpiredHolds'
import { cancelUnpaidBookings } from './jobs/cancelUnpaidBookings'
import { sendDepartureReminders } from './jobs/sendDepartureReminders'
import { completeTrips } from './jobs/completeTrips'

const port = process.env.PORT ? Number(process.env.PORT) : 4000

const app = createApp()

app.listen(port, () => {
  console.log(`API listening on http://localhost:${port}`)
})

// Runs the trip-generation job on a schedule when this API is deployed
// as a long-running process. Set ENABLE_CRON=false if trips are
// instead generated by an external scheduler (e.g. a Railway cron job
// invoking `node dist/jobs/generateTrips.js` directly) — running both
// is harmless (the job is idempotent) but redundant.
if (process.env.ENABLE_CRON !== 'false') {
  const schedule = process.env.TRIP_GENERATION_CRON ?? '0 2 * * *' // daily at 02:00
  cron.schedule(schedule, () => {
    generateUpcomingTrips().catch((err) => console.error('[cron] generateUpcomingTrips failed', err))
  })
  console.log(`[cron] trip generation scheduled: "${schedule}"`)

  const purgeSchedule = process.env.PURGE_HOLDS_CRON ?? '*/5 * * * *' // every 5 minutes
  cron.schedule(purgeSchedule, () => {
    purgeExpiredHolds().catch((err) => console.error('[cron] purgeExpiredHolds failed', err))
  })
  console.log(`[cron] expired-hold cleanup scheduled: "${purgeSchedule}"`)

  const cancelUnpaidSchedule = process.env.CANCEL_UNPAID_CRON ?? '*/5 * * * *' // every 5 minutes
  cron.schedule(cancelUnpaidSchedule, () => {
    cancelUnpaidBookings().catch((err) => console.error('[cron] cancelUnpaidBookings failed', err))
  })
  console.log(`[cron] unpaid-booking cancellation scheduled: "${cancelUnpaidSchedule}"`)

  const reminderSchedule = process.env.DEPARTURE_REMINDER_CRON ?? '*/5 * * * *' // every 5 minutes
  cron.schedule(reminderSchedule, () => {
    sendDepartureReminders().catch((err) => console.error('[cron] sendDepartureReminders failed', err))
  })
  console.log(`[cron] departure-reminder scheduled: "${reminderSchedule}"`)

  const completeTripsSchedule = process.env.TRIP_COMPLETION_CRON ?? '*/5 * * * *' // every 5 minutes
  cron.schedule(completeTripsSchedule, () => {
    completeTrips().catch((err) => console.error('[cron] completeTrips failed', err))
  })
  console.log(`[cron] trip-completion scheduled: "${completeTripsSchedule}"`)
}
